#!/bin/bash

SAVEIFS=$IFS
IFS=$(echo -en "\n\b")


if [[ $2 == '/home/nadim/Downloads' ]] ; then
	for f in ${@:3} ; do
		X=${f#\'}
		X=${X%\'}
		mv $2/$X $2/$1/
	done
else
	echo ** not in Downloads directory **
fi

IFS=$SAVEIFS

