#!/bin/bash

#echo "$2" | cut -d : -f $1

# handle files containing : or :: in their name
#perl -e 'no warnings experimental::alpha_assertions ; print [split /(*negative_lookbehind::):(*negative_lookahead::)/, $ARGV[1]]->[$ARGV[0] - 1]' $1 "$2"
perl -e 'print [split /(?<!:):(?!:)/, $ARGV[1]]->[$ARGV[0] - 1]' $1 "$2"
