#!/bin/bash

countdown()
(
# $1 is minutes
[[ "$2" ]] && message="$2" ; [[ "$3" ]] && end_message="$3"

IFS=:
set -- $*
secs=$(( ${1#0} * 3600 + ${2#0} * 60 + ${3#0} ))

while [ $secs -gt 0 ] ; do
	printf "\r$message %02d:%02d:%02d" $((secs/3600)) $(( (secs/60)%60)) $((secs%60))
	secs=$(( $secs - 1 ))
	sleep 1
done

printf "\r$message%02d:%02d:%02d\n" 0 0 0 

[[ "$end_message" ]] && echo -e "$end_message" 

)

countdown "$@"

