#!/bin/bash

piper $@ \
'^l' yellow \
'd|-' yellow \
'([rwxt-]{3})+' rgb123 \
'[0-9]+\s' grey9  \
"$USER\s+[_a-zA-Z]+" grey7 \
'[0-9.]+K\s' grey9  \
'[5-9][0-9]{2}K\s' rgb033 \
'[0-9.]+M\s' rgb040 \
'[0-9.]+G\s' rgb540 \
'.+?((\d\d:\d\d)|([0-9]{4}))' grey5 \
'[0-9.]+\s' red 


